# Generated by Django 5.1.2 on 2024-12-26 00:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_method',
            field=models.TextField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='terms',
            field=models.TextField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateField(default=datetime.date(2024, 12, 25)),
        ),
    ]
