# Generated by Django 5.1.2 on 2025-01-09 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0008_purchaseorder_created_at_purchaseorder_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_quantity', models.PositiveIntegerField()),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('is_accepted', models.BooleanField(default=True)),
                ('rejection_reason', models.CharField(choices=[('EXPIRED', 'Expired'), ('SHORT_DATE', 'Short Date'), ('DAMAGED', 'Damaged'), ('LATE_DELIVERY', 'Late Delivery'), ('OTHER', 'Other')], max_length=255)),
                ('po_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiving_logs', to='purchase_orders.purchaseorderitem')),
            ],
        ),
    ]
