# Generated by Django 5.1.2 on 2024-11-18 04:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('item_id', models.PositiveIntegerField(help_text='Unique sequential numeric identifier for the inventory item.', primary_key=True, serialize=False, unique=True)),
                ('item_name', models.CharField(help_text='Name of the inventory item.', max_length=255)),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Cost per unit.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Selling price per unit.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('quantity', models.PositiveIntegerField(help_text='Current stock quantity.')),
                ('barcode', models.CharField(blank=True, help_text='Optional barcode identifier.', max_length=255, null=True, unique=True)),
                ('min_stock_level', models.IntegerField(default=1, help_text='Minimum stock level threshold.')),
                ('max_stock_level', models.IntegerField(default=100, help_text='Maximum stock level threshold.')),
                ('product_category', models.CharField(help_text='Category of the product.', max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', help_text='Current status of the item.', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update.')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'ordering': ['item_name'],
            },
        ),
    ]
