# Generated by Django 5.1.2 on 2025-01-11 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_inventoryitem_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='unit_cost',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='unit_price',
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, help_text='Quantity for this batch.', max_digits=10)),
                ('expiration_date', models.DateField(blank=True, help_text='Expiration date for this batch.', null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, help_text='Cost per unit for this batch.', max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Selling price per unit for this batch.', max_digits=10)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['expiration_date'],
            },
        ),
    ]
