# Generated by Django 5.1.2 on 2025-01-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_remove_batch_unit_price_inventoryitem_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='unit_cost',
        ),
        migrations.AddField(
            model_name='batch',
            name='batch_unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost per unit for this batch.', max_digits=10),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Standard cost per unit.', max_digits=10),
        ),
    ]
