# Generated by Django 5.1.2 on 2025-01-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventoryitem_item_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='barcode',
            field=models.CharField(blank=True, help_text='Optional barcode identifier.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, help_text='Cost per unit.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Selling price per unit.', max_digits=10),
        ),
    ]
