# Generated by Django 5.1.2 on 2025-01-10 23:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventoryitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='measurement_type',
            field=models.CharField(choices=[('count', 'Count-based'), ('weight', 'Weight-based')], default='count', help_text='Indicates whether the item is count-based or weight-based.', max_length=10),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='max_stock_level',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Maximum stock level threshold. Allows fractions for weight-based items.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='min_stock_level',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Minimum stock level threshold. Allows fractions for weight-based items.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Current stock quantity. Allows fractions for weight-based items.', max_digits=10),
        ),
    ]
