# Generated by Django 5.1.2 on 2025-01-11 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventoryitem_measurement_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='has_issues',
            field=models.BooleanField(default=False, help_text='Indicates if the item has issues needing review.'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='issue_reasons',
            field=models.TextField(blank=True, help_text='Reasons for flagging this item as having issues.', null=True),
        ),
    ]
