# Generated by Django 5.1.2 on 2025-01-11 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventoryitem_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='product_category',
            field=models.CharField(choices=[('BAKERY', 'Bakery'), ('BEVERAGE', 'Beverage'), ('CANDY', 'Candy'), ('CHANGEMAKER', 'Changemaker'), ('CHOCOLATE', 'Chocolate'), ('DELI COLD', 'Deli Cold'), ('DELI GENERAL', 'Deli General'), ('DELI SUPPLY', 'Deli Supply'), ('FOOD', 'Food'), ('GROCERY', 'Grocery'), ('GUM & MINT', 'Gum & Mint'), ('HBA', 'Hba'), ('IMPORT', 'Import'), ('NON CHOCOLATE', 'Non Chocolate'), ('ORGANIC', 'Organic'), ('PAPER GOODS', 'Paper Goods'), ('PEG BAG', 'Peg Bag'), ('PET FOOD', 'Pet Food'), ('ROLLING PAPER', 'Rolling Paper'), ('SNACKS', 'Snacks'), ('SYSTEM', 'System'), ('THEATER', 'Theater'), ('TOY', 'Toy'), ('WIRELESS', 'Wireless')], help_text='Category of the product.', max_length=100),
        ),
    ]
