# Generated by Django 5.1.2 on 2025-01-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_inventoryitem_expiration_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed selling price per unit, independent of batches.', max_digits=10),
        ),
    ]
