# Generated by Django 5.1.2 on 2024-11-18 04:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+123456789'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('terms', models.CharField(choices=[('NET7', 'Net 7 (Payment due in 7 days)'), ('NET14', 'Net 14 (Payment due in 14 days)'), ('NET30', 'Net 30 (Payment due in 30 days)'), ('NET45', 'Net 45 (Payment due in 30 days)'), ('NET60', 'Net 60 (Payment due in 60 days)'), ('NET90', 'Net 90 (Payment due in 90 days)'), ('COD', 'Cash on Delivery'), ('PREPAID', 'Prepaid (Payment in advance)'), ('OTHER', 'Other (Specify in Notes)')], default='NET30', help_text='Select the payment terms for this vendor', max_length=20)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CREDIT', 'Credit Card'), ('CHECK', 'Check'), ('BANK', 'Bank Transfer'), ('OTHER', 'Other (Specify in Notes)')], default='CHECK', help_text='Select the payment method for this vendor', max_length=10)),
                ('website', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', help_text='Current status of the item.', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost Price')),
                ('last_purchased_date', models.DateField(blank=True, null=True, verbose_name='Last Purchased Date')),
                ('purchase_order_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Purchase Order Number')),
                ('date_placed', models.DateField(blank=True, null=True, verbose_name='Date Placed')),
                ('date_received', models.DateField(blank=True, null=True, verbose_name='Date Received')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem', verbose_name='Item')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendors.vendor', verbose_name='Vendor')),
            ],
        ),
    ]
