# Generated by Django 5.1.2 on 2025-01-06 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0005_purchaseorder_items_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='items_count',
        ),
    ]
