# Generated by Django 5.1.2 on 2025-01-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0006_remove_purchaseorder_items_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='items_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
