# Generated by Django 5.1.2 on 2025-01-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0010_alter_receivinglog_rejection_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receivinglog',
            options={'verbose_name': 'Receiving Log', 'verbose_name_plural': 'Receiving Logs'},
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='expiration_date',
            field=models.DateField(blank=True, help_text='Expiration date for this batch.', null=True),
        ),
    ]
